version: '3'

networks:
  main:

volumes:
  postgres_data:

services:
  db:
    image: postgres:10.3
    volumes:
      - postgres_data:/var/lib/postgresl/data/
    networks:
      - main
  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python /app/manage.py migrate --noinput
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db
