# Generated by Django 2.0.2 on 2018-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap_universiada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('ultima_comida', models.BooleanField(default=False)),
                ('institucion', models.CharField(max_length=255)),
                ('tipos', models.CharField(choices=[('deportista', 'DEPORTISTA'), ('entrenador', 'ENTRENADOR'), ('juez', 'JUEZ'), ('delegado', 'DELEGADO'), ('coordinador', 'COORDINADOR'), ('comisionado-tecnico', 'COMISIONADO TÉCNICO'), ('medico', 'MÉDICO'), ('comite-organizador', 'COMITÉ ORGANIZADOR')], default='deportista', max_length=19)),
            ],
        ),
    ]
