# Generated by Django 2.0.2 on 2018-03-13 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='uiid',
            field=models.UUIDField(default=uuid.UUID('cbbf0376-8e6f-4d55-89dc-9a2a52037320'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='estatus',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ultima_comida',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
