# Generated by Django 2.0.2 on 2018-03-14 02:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0002_auto_20180313_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='uiid',
        ),
        migrations.AddField(
            model_name='participante',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
