# Generated by Django 2.0.2 on 2018-03-14 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0003_auto_20180313_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
